// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: spacex/api/device/dish_config.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DishConfig_SnowMeltMode int32

const (
	DishConfig_AUTO       DishConfig_SnowMeltMode = 0
	DishConfig_ALWAYS_ON  DishConfig_SnowMeltMode = 1
	DishConfig_ALWAYS_OFF DishConfig_SnowMeltMode = 2
)

// Enum value maps for DishConfig_SnowMeltMode.
var (
	DishConfig_SnowMeltMode_name = map[int32]string{
		0: "AUTO",
		1: "ALWAYS_ON",
		2: "ALWAYS_OFF",
	}
	DishConfig_SnowMeltMode_value = map[string]int32{
		"AUTO":       0,
		"ALWAYS_ON":  1,
		"ALWAYS_OFF": 2,
	}
)

func (x DishConfig_SnowMeltMode) Enum() *DishConfig_SnowMeltMode {
	p := new(DishConfig_SnowMeltMode)
	*p = x
	return p
}

func (x DishConfig_SnowMeltMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DishConfig_SnowMeltMode) Descriptor() protoreflect.EnumDescriptor {
	return file_spacex_api_device_dish_config_proto_enumTypes[0].Descriptor()
}

func (DishConfig_SnowMeltMode) Type() protoreflect.EnumType {
	return &file_spacex_api_device_dish_config_proto_enumTypes[0]
}

func (x DishConfig_SnowMeltMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DishConfig_SnowMeltMode.Descriptor instead.
func (DishConfig_SnowMeltMode) EnumDescriptor() ([]byte, []int) {
	return file_spacex_api_device_dish_config_proto_rawDescGZIP(), []int{0, 0}
}

type DishConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SnowMeltMode      DishConfig_SnowMeltMode `protobuf:"varint,1,opt,name=snow_melt_mode,json=snowMeltMode,proto3,enum=SpaceX.API.Device.DishConfig_SnowMeltMode" json:"snow_melt_mode,omitempty"`
	ApplySnowMeltMode bool                    `protobuf:"varint,1001,opt,name=apply_snow_melt_mode,json=applySnowMeltMode,proto3" json:"apply_snow_melt_mode,omitempty"`
}

func (x *DishConfig) Reset() {
	*x = DishConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spacex_api_device_dish_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DishConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishConfig) ProtoMessage() {}

func (x *DishConfig) ProtoReflect() protoreflect.Message {
	mi := &file_spacex_api_device_dish_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishConfig.ProtoReflect.Descriptor instead.
func (*DishConfig) Descriptor() ([]byte, []int) {
	return file_spacex_api_device_dish_config_proto_rawDescGZIP(), []int{0}
}

func (x *DishConfig) GetSnowMeltMode() DishConfig_SnowMeltMode {
	if x != nil {
		return x.SnowMeltMode
	}
	return DishConfig_AUTO
}

func (x *DishConfig) GetApplySnowMeltMode() bool {
	if x != nil {
		return x.ApplySnowMeltMode
	}
	return false
}

var File_spacex_api_device_dish_config_proto protoreflect.FileDescriptor

var file_spacex_api_device_dish_config_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x70, 0x61, 0x63, 0x65, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50,
	0x49, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x44, 0x69, 0x73,
	0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x50, 0x0a, 0x0e, 0x73, 0x6e, 0x6f, 0x77, 0x5f,
	0x6d, 0x65, 0x6c, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x2a, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x58, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53,
	0x6e, 0x6f, 0x77, 0x4d, 0x65, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x0c, 0x73, 0x6e, 0x6f,
	0x77, 0x4d, 0x65, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x61, 0x70, 0x70,
	0x6c, 0x79, 0x5f, 0x73, 0x6e, 0x6f, 0x77, 0x5f, 0x6d, 0x65, 0x6c, 0x74, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0xe9, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x53,
	0x6e, 0x6f, 0x77, 0x4d, 0x65, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x37, 0x0a, 0x0c, 0x53,
	0x6e, 0x6f, 0x77, 0x4d, 0x65, 0x6c, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x41,
	0x55, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4c, 0x57, 0x41, 0x59, 0x53, 0x5f,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x4c, 0x57, 0x41, 0x59, 0x53, 0x5f, 0x4f,
	0x46, 0x46, 0x10, 0x02, 0x42, 0x17, 0x5a, 0x15, 0x73, 0x70, 0x61, 0x63, 0x65, 0x78, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spacex_api_device_dish_config_proto_rawDescOnce sync.Once
	file_spacex_api_device_dish_config_proto_rawDescData = file_spacex_api_device_dish_config_proto_rawDesc
)

func file_spacex_api_device_dish_config_proto_rawDescGZIP() []byte {
	file_spacex_api_device_dish_config_proto_rawDescOnce.Do(func() {
		file_spacex_api_device_dish_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_spacex_api_device_dish_config_proto_rawDescData)
	})
	return file_spacex_api_device_dish_config_proto_rawDescData
}

var file_spacex_api_device_dish_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spacex_api_device_dish_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spacex_api_device_dish_config_proto_goTypes = []interface{}{
	(DishConfig_SnowMeltMode)(0), // 0: SpaceX.API.Device.DishConfig.SnowMeltMode
	(*DishConfig)(nil),           // 1: SpaceX.API.Device.DishConfig
}
var file_spacex_api_device_dish_config_proto_depIdxs = []int32{
	0, // 0: SpaceX.API.Device.DishConfig.snow_melt_mode:type_name -> SpaceX.API.Device.DishConfig.SnowMeltMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spacex_api_device_dish_config_proto_init() }
func file_spacex_api_device_dish_config_proto_init() {
	if File_spacex_api_device_dish_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spacex_api_device_dish_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DishConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spacex_api_device_dish_config_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spacex_api_device_dish_config_proto_goTypes,
		DependencyIndexes: file_spacex_api_device_dish_config_proto_depIdxs,
		EnumInfos:         file_spacex_api_device_dish_config_proto_enumTypes,
		MessageInfos:      file_spacex_api_device_dish_config_proto_msgTypes,
	}.Build()
	File_spacex_api_device_dish_config_proto = out.File
	file_spacex_api_device_dish_config_proto_rawDesc = nil
	file_spacex_api_device_dish_config_proto_goTypes = nil
	file_spacex_api_device_dish_config_proto_depIdxs = nil
}
